[tool.poetry]
name = "gil"
version = "0.1.0"
description = ""
authors = ["Tjark Ziehm <me@tjarkziehm.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
